### ISSUE TITLE
Runtime error occur

### ISSUE THREAD

**Issue by mrgreen3325** [tanjeffreyz/yolo-v1#1]
Hello. Thanks for your code.
I ran the code. However, there is an error.
RuntimeError: Function 'MseLossBackward0' returned nan values in its 0th output.

**Comment by Yancy456** [comment]
I analysed the code. The problem is because of  nan value in data causing by data augment in file data.py. The normalization will set some values of an image into nagetive and thus result adjust_hue to produce nan values. The solution is simple, exchanging the block of if self.augment and if self.normalize.
![image](https://github.com/tanjeffreyz/yolo-v1/assets/10668896/38d3c5ea-615e-4858-8f1c-6a0dcbdf7d8e)

**Comment by tanjeffreyz** [comment]
Great catch! Thanks a lot for sharing the fix
